version: "3.9"

networks:
    laravel:
        name: laravel

services:

    nginx:
        build:
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            - mysql
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    php:
        build:
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    mysql:
        image: mysql:8.0.27
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel